services:
  - type: web
    name: rigscouter-ai-database
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000