services:
  - type: web
    name: rigscouter-ai-database
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000